### ISSUE TITLE
Questions about the simu sw, and calibrations

### ISSUE THREAD

**Issue by shinong** [Ttl/vna#1]
Hi, 
First of all, thank you so much for sharing the design of your self-designed VNA. I did learn a lot from your docs. And it helped me a lot on my thesis research. However, I do have some questions about your documents in this project. 
First, what is the simulation software you used in your design stage, and how you generated your PCB layout? Did you calculate the width of the trace and use this parameter for manual routing or you used the simu software to generate the layout directly? 
Second, for the calibration method. You used the 3-term error model for 1 port cali, and you used magnitudes only for calibration. I am not clear about how phase data is used for calibration? Cause you mentioned in another project that VNA is more accurate than SNA because of the phase correction. 
Those are all questions I have for now. Could you please take some time to look at them and reply me whenever you are convenient? Really appreciated!

Thanks,
Shinong

**Comment by Ttl** [comment]
There isn't that much to simulate. Most is done just with pen and paper. Couplers were simulated using EM simulator. Line width was calculated to give 50 ohm impedance and the layout was done manually in KiCad.

Phases are needed because in general linear two ports have phases and we need to solve the coefficients of the error network during the calibration.
